//Check the token

const START_TOKEN_VALIDATION="START_TOKEN_VALIDATION";
const TOKEN_VALIDATION_SUCCESS="TOKEN_VALIDATION_SUCCESS";
const TOKEN_VALIDATION_FAIL="TOKEN_VALIDATION_FAIL";
const TOKEN_INVALID="TOKEN_INVALID";
const TOKEN_SETTER="TOKEN_SETTER"

const REPO_SEARCH_START="REPO_SEARCH_START";
const REPO_SEARCH_SUCCESS="REPO_SEARCH_SUCCESS";
const REPO_SEARCH_FAIL="REPO_SEARCH_FAIL";


export{
    START_TOKEN_VALIDATION,TOKEN_VALIDATION_SUCCESS,TOKEN_VALIDATION_FAIL,TOKEN_INVALID,TOKEN_SETTER,
    REPO_SEARCH_START,REPO_SEARCH_SUCCESS,REPO_SEARCH_FAIL
}